Repository DTStack/dt-react-component, pull requests merged in 2021-07, with the labels that each got.

#110 fix: rename FullScreenButton to Fullscreen
  src/components/fullscreen/__tests__/index.test.tsx
  src/components/fullscreen/index.tsx
  src/components/index.tsx
  src/components/toolModal/index.tsx
  src/stories/fullscreen.stories.tsx
Labels: bug

#113 fix: gulp to complier
  .gitignore
  css-plugin.js
  gulpfile.js
  package.json
  tsconfig.build.json
  tsconfig.esm.json
  tsconfig.json
  tsconfig.lib.json
Labels: build

#112 Feat 2.0.4 progress line
  src/components/progressLine/index.scss
  src/components/progressLine/index.tsx
  src/stories/progressLine.stories.tsx
Labels: duplicate, enhancement
