Repository DTStack/dt-react-component, pull requests merged in 2023-11, with the labels that each got.

#402 feat: import highlight core only
  src/markdownRender/extensions/index.ts
Labels: Improve Component

#403 feat: add sideEffects conf to improve treeShaking
  package.json
Labels: enhancement

#405 feat: add search component on sidebar
  .dumi/theme/slots/Sidebar/index.scss
  .dumi/theme/slots/Sidebar/index.tsx
Labels: documentation

#408 docs: update Tree&Details builtin components
  .dumi/theme/builtins/Details.tsx
  .dumi/theme/builtins/index.less
  docs/guide/componentDev.md
  package.json
  pnpm-lock.yaml
  src/form/index.md
  src/markdownRender/demos/basic.tsx
Labels: documentation
