Repository DTStack/dt-react-component, pull requests merged in 2023-06, with the labels that each got.

#350 fix: fixed Modal.Form ts problems
  src/modal/demos/advance.tsx
  src/modal/demos/basics.tsx
  src/modal/demos/classComponent.tsx
  src/modal/form.tsx
  src/modal/index.md
Labels: bug

#351 feat: listen for parent element size changes
  src/ellipsisText/demos/watchParent.tsx
  src/ellipsisText/index.md
  src/ellipsisText/index.tsx
Labels: Improve Component

#353 [WIP]feat(Form): support title, footer, summary on Form.Table
  src/form/demos/footer.tsx
  src/form/index.md
  src/form/table.tsx
Labels: enhancement

#354 feat: support titleTooltip attribute in form table
  src/form/demos/basic.tsx
  src/form/index.md
  src/form/index.scss
  src/form/table.tsx
Labels: Improve Component

#356 feat: add table component
  src/index.ts
  src/table/__tests__/table.test.tsx
  src/table/demos/basic.tsx
  src/table/index.md
  src/table/index.scss
  src/table/index.tsx
Labels: new component
