Repository DTStack/dt-react-component, pull requests merged in 2023-05, with the labels that each got.

#331 docs: improve form.table doc
  src/form/demos/basic.tsx
Labels: documentation

#325 Refactor/spread sheet
  src/spreadSheet/__tests__/index.test.tsx
  src/spreadSheet/demos/basic.tsx
  src/spreadSheet/index.md
  src/spreadSheet/index.tsx
  src/spreadSheet/style.scss
Labels: documentation, refactor

#329 feat: refactor copyIcon component
  package.json
  pnpm-lock.yaml
  src/copy/__tests__/copy.test.tsx
  src/copy/demos/basic.tsx
  src/copy/demos/custom.tsx
  src/copy/index.md
  src/copy/index.tsx
  src/copy/style.scss
  src/copyIcon/index.tsx
  src/copyIcon/style.scss
  src/index.ts
Labels: refactor

#334 docs: v4 site upgrade
  docs/guide/CONTRIBUTING.md
  docs/guide/componentDev.md
  docs/guide/index.md
  docs/guide/updateLog.md
Labels: documentation

#332 docs: improve getting-started doc
  .dumi/theme/slots/Footer/index.scss
  README-zh_CN.md
  README.md
  docs/guide/CONTRIBUTING.md
  docs/guide/index.md
Labels: documentation

#335 docs: improve component-development doc
  docs/guide/componentDev.md
Labels: documentation

#338 docs: migration v4
  docs/guide/migration-v4.md
  docs/guide/updateLog.md
Labels: doc

#340 docs: #339 hooks sort
  .github/workflows/CD.yml
  .github/workflows/CI.yml
  README-zh_CN.md
  README.md
  src/cookies/index.md
  src/switchWindow/index.md
  src/useList/index.md
Labels: doc

#341 feat: #337 add statusTag loading
  src/statusTag/__tests__/index.test.tsx
  src/statusTag/demos/loading.tsx
  src/statusTag/index.md
  src/statusTag/index.tsx
Labels: Improve Component

#342 fix: stale params when revalidate
  src/useList/__tests__/useList.test.ts
  src/useList/index.ts
Labels: bug

#344 build: update release
  scripts/release.sh
Labels: build

#345 build: add standard-version
  package.json
  pnpm-lock.yaml
Labels: build

#348 fix: improve footer copyright
  .dumi/theme/slots/Footer/index.tsx
  .dumirc.ts
  tsconfig.json
Labels: documentation

#347 fix(blockHeader): improve height of small blockHeader
  src/blockHeader/style.scss
Labels: bug
