Repository DTStack/dt-react-component, pull requests merged in 2023-04, with the labels that each got.

#296 feat(dropdown): develop `dropdown.select`
  package.json
  pnpm-lock.yaml
  src/dropdown/__tests__/__snapshots__/dropdown.test.tsx.snap
  src/dropdown/__tests__/dropdown.test.tsx
  src/dropdown/demos/basic.tsx
  src/dropdown/demos/submit.tsx
  src/dropdown/demos/virtual.tsx
  src/dropdown/index.md
  src/dropdown/index.tsx
  src/dropdown/select.tsx
  src/dropdown/style.scss
  src/index.ts
  src/mulSelectDropdown/__tests__/mulSelectDropdown.test.tsx
  src/mulSelectDropdown/index.md
  src/mulSelectDropdown/index.tsx
  src/mulSelectDropdown/style.scss
Labels: refactor

#293 feat(Form): develop `Form.Table`
  package.json
  pnpm-lock.yaml
  src/form/__tests__/__snapshots__/table.test.tsx.snap
  src/form/__tests__/table.test.tsx
  src/form/demos/basic.tsx
  src/form/demos/check.tsx
  src/form/demos/data.ts
  src/form/demos/related.tsx
  src/form/demos/rules.tsx
  src/form/index.md
  src/form/index.scss
  src/form/index.tsx
  src/form/table.tsx
  src/index.ts
Labels: new component

#306 chore: adjust sidebar's fontSize
  .dumi/theme/style/const.scss
Labels: documentation

#309 fix: fix antd dynamic import style
  .dumi/global.less
Labels: bug

#307 refactor(markdownRender): improve markdownRender
  src/markdownRender/__tests__/__snapshots__/markdownRender.test.tsx.snap
  src/markdownRender/__tests__/markdownRender.test.tsx
  src/markdownRender/demos/basic.tsx
  src/markdownRender/demos/dark.tsx
  src/markdownRender/demos/sql.tsx
  src/markdownRender/extensions/index.ts
  src/markdownRender/index.md
  src/markdownRender/index.tsx
Labels: refactor

#300 Feat v4 table action menu
  src/collapsibleActionItems/__tests__/index.test.tsx
  src/collapsibleActionItems/index.md
  src/collapsibleActionItems/index.tsx
  src/index.ts
Labels: new component

#294 refactor cookies
  src/cookies/__tests__/cookies.test.tsx
  src/cookies/demos/advanced.tsx
  src/cookies/demos/basic.tsx
  src/cookies/index.md
  src/cookies/index.tsx
  src/index.ts
  src/utils/index.ts
Labels: refactor

#304 WIP refactor: fullscreen component refactor
  src/fullscreen/__tests__/__snapshots__/index.test.tsx.snap
  src/fullscreen/__tests__/index.test.tsx
  src/fullscreen/demos/basic.tsx
  src/fullscreen/demos/custom.tsx
  src/fullscreen/demos/local.tsx
  src/fullscreen/demos/theme.tsx
  src/fullscreen/icon.tsx
  src/fullscreen/index.md
  src/fullscreen/index.tsx
  src/fullscreen/style.scss
Labels: refactor

#310 Refactor/status tag
  src/blockHeader/index.tsx
  src/statusTag/demos/basic.tsx
  src/statusTag/demos/border.tsx
  src/statusTag/demos/colorful.tsx
  src/statusTag/demos/status.tsx
  src/statusTag/index.md
  src/statusTag/index.tsx
Labels: documentation, refactor

#317 Refactor/modal with form
  package.json
  pnpm-lock.yaml
  src/index.ts
  src/modal/__tests__/modalWithForm.test.tsx
  src/modal/demos/advance.tsx
  src/modal/demos/basics.tsx
  src/modal/form.tsx
  src/modal/index.md
  src/modal/index.tsx
  src/modalWithForm/index.md
  src/modalWithForm/index.tsx
  src/utils/__tests__/uttils.tests.tsx
  src/utils/antdProps.ts
  src/utils/index.ts
Labels: refactor

#303 refactor: ellipsisTest component, improve documentation
  src/ellipsisText/__tests__/ellipsisText.test.tsx
  src/ellipsisText/demos/basic.tsx
  src/ellipsisText/demos/flex.tsx
  src/ellipsisText/demos/inlineElement.tsx
  src/ellipsisText/demos/maxWidth.tsx
  src/ellipsisText/demos/multiple.tsx
  src/ellipsisText/demos/valueType.tsx
  src/ellipsisText/index.md
  src/ellipsisText/index.tsx
  src/ellipsisText/style.scss
Labels: refactor

#318 feat: optimize NotFound
  src/notFound/__tests__/notFound.test.tsx
  src/notFound/index.md
  src/notFound/index.tsx
  src/notFound/style.scss
Labels: refactor

#320 Feat progress bar
  src/progressBar/__test__/progressBar.test.tsx
  src/progressBar/index.md
  src/progressBar/index.tsx
  src/progressBar/style.scss
Labels: refactor

#324 Refactor/resize
  src/resize/__tests__/index.test.tsx
  src/resize/demos/basic.tsx
  src/resize/demos/observerEle.tsx
  src/resize/index.md
  src/resize/index.tsx
Labels: documentation, refactor, unit test

#328 fix: add padding for errorBoundary demos
  src/errorBoundary/demos/basic.tsx
  src/errorBoundary/demos/customErrorPage.tsx
Labels: bug

#327 refactor: switchWindow to refactor as hooks
  src/index.ts
  src/switchWindow/__tests__/switchWindow.test.tsx
  src/switchWindow/demos/basic.tsx
  src/switchWindow/index.md
  src/switchWindow/index.tsx
Labels: documentation, refactor, unit test

#316 feat(input): develop input.match
  src/index.ts
  src/input/__tests__/__snapshots__/match.test.tsx.snap
  src/input/__tests__/match.test.tsx
  src/input/demos/basic.tsx
  src/input/demos/filterOptions.tsx
  src/input/icons.tsx
  src/input/index.md
  src/input/index.tsx
  src/input/match.scss
  src/input/match.tsx
  src/multiSearchInput/__tests__/__snapshots__/multiSearchInput.test.tsx.snap
  src/multiSearchInput/__tests__/multiSearchInput.test.tsx
  src/multiSearchInput/demos/actions.tsx
  src/multiSearchInput/demos/basic.tsx
  src/multiSearchInput/index.md
  src/multiSearchInput/index.tsx
Labels: refactor

#297 feat(useList): develop useList
  src/index.ts
  src/useList/__tests__/useList.test.ts
  src/useList/demos/basic.tsx
  src/useList/demos/data.ts
  src/useList/demos/options.tsx
  src/useList/demos/sort.tsx
  src/useList/index.md
  src/useList/index.ts
Labels: new component

#330 Feat v4 slide pane
  package.json
  pnpm-lock.yaml
  src/fullscreen/__tests__/index.test.tsx
  src/slidePane/__tests/__snapshots__/index.test.tsx.snap
  src/slidePane/__tests/index.test.tsx
  src/slidePane/demos/basic.tsx
  src/slidePane/index.md
  src/slidePane/index.tsx
  src/slidePane/style.scss
Labels: documentation, refactor, unit test
